export const tableHeaders = [
  {
    Header: 'SKU',
    accessor: 'SKU',
    sortType: 'basic',
  },
  {
    Header: 'MPID',
    accessor: 'MPID',
    sortType: 'basic',
  },
  {
    Header: 'Record Type',
    accessor: 'Record Type',
    sortType: 'basic',
  },
  {
    Header: 'Asset Type',
    accessor: 'Asset Type',
    sortType: 'basic',
  },
  {
    Header: 'Pipeline',
    accessor: 'Pipeline',
    sortType: 'basic',
  },
  {
    Header: 'Step',
    accessor: 'Step',
    sortType: 'basic',
  },
  {
    Header: 'Status',
    accessor: 'Status',
    sortType: 'basic',
  },
  {
    Header: 'Days in Status',
    accessor: 'Days in Status',
    sortType: 'basic',
  },
  {
    Header: 'Round',
    accessor: 'Round',
    sortType: 'basic',
  },
  {
    Header: 'Assigned to',
    accessor: 'Assigned to',
    sortType: 'basic',
  },
]

export const tableData = [
  {
    'SKU': '101',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '111',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '121',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '131',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '141',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '151',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '161',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '171',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '181',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '191',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '110',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '111',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '112',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '113',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
  {
    'SKU': '114',
    'MPID': '###' ,
    'Record Type': 'Request',
    'Asset Type': 'Zie',
    'Pipeline': 'Swap-in',
    'Step': 'Product Swap',
    'Status': 'In Progress',
    'Days in Status': 1,
    'Round': 0,
    'Assigned to': 'Vendor',
    'subRows': [
      {
        'SKU': '111',
        'MPID': '###' ,
        'Record Type': 'Model',
        'Asset Type': 'General',
        'Pipeline': 'Model Creation',
        'Status': 'Complete',
      },
      {
        'Record Type': 'Template',
        'Asset Type': 'Zie',
        'Pipeline': 'ZIE Template Creation',
        'Status': 'Complete',
      },
    ]
  },
]